dutylist["Sastasha"] = "Sastasha"
dutylist["The Tam-Tara Deepcroft"] = "The Tam-Tara Deepcroft"
dutylist["Copperbell Mines"] = "Copperbell Mines"
dutylist["Halatali"] = "Halatali"
dutylist["The Thousand Maws of Toto-Rak"] = "The Thousand Maws of Toto-Rak"
dutylist["Haukke Manor"] = "Haukke Manor"
dutylist["Brayflox's Longstop"] = "Brayflox's Longstop"
dutylist["The Sunken Temple of Qarn"] = "The Sunken Temple of Qarn"
dutylist["Cutter's Cry"] = "Cutter's Cry"
dutylist["The Stone Vigil"] = "The Stone Vigil"
dutylist["Dzemael Darkhold"] = "Dzemael Darkhold"
dutylist["The Aurum Vale"] = "The Aurum Vale"
dutylist["Castrum Meridianum"] = "Castrum Meridianum"
dutylist["The Praetorium"] = "The Praetorium"
dutylist["The Wanderer's Palace"] = "The Wanderer's Palace"
dutylist["Amdapor Keep"] = "Amdapor Keep"
dutylist["Pharos Sirius"] = "Pharos Sirius"
dutylist["Copperbell Mines (Hard)"] = "Copperbell Mines (Hard)"
dutylist["Haukke Manor (Hard)"] = "Haukke Manor (Hard)"
dutylist["The Lost City of Amdapor"] = "The Lost City of Amdapor"
dutylist["Halatali (Hard)"] = "Halatali (Hard)"
dutylist["Brayflox's Longstop (Hard)"] = "Brayflox's Longstop (Hard)"
dutylist["Hullbreaker Isle"] = "Hullbreaker Isle"
dutylist["The Tam-Tara Deepcroft (Hard)"] = "The Tam-Tara Deepcroft (Hard)"
dutylist["The Stone Vigil (Hard)"] = "The Stone Vigil (Hard)"
dutylist["Snowcloak"] = "Snowcloak"
dutylist["Sastasha (Hard)"] = "Sastasha (Hard)"
dutylist["The Sunken Temple of Qarn (Hard)"] = "The Sunken Temple of Qarn (Hard)"
dutylist["The Keeper of the Lake"] = "The Keeper of the Lake"
dutylist["The Wanderer's Palace (Hard)"] = "The Wanderer's Palace (Hard)"
dutylist["Amdapor Keep (Hard)"] = "Amdapor Keep (Hard)"
dutylist["The Bowl of Embers"] = "The Bowl of Embers"
dutylist["The Navel"] = "The Navel"
dutylist["The Howling Eye"] = "The Howling Eye"
dutylist["The Porta Decumana"] = "The Porta Decumana"
dutylist["The Bowl of Embers (Hard)"] = "The Bowl of Embers (Hard)"
dutylist["The Howling Eye (Hard)"] = "The Howling Eye (Hard)"
dutylist["The Navel (Hard)"] = "The Navel (Hard)"
dutylist["Thornmarch (Hard)"] = "Thornmarch (Hard)"
dutylist["A Relic Reborn the Chimera"] = "A Relic Reborn: the Chimera"
dutylist["A Relic Reborn the Hydra"] = "A Relic Reborn: the Hydra"
dutylist["The Whorleater (Hard)"] = "The Whorleater (Hard)"
dutylist["Battle on the Big Bridge"] = "Battle on the Big Bridge"
dutylist["The Striking Tree (Hard)"] = "The Striking Tree (Hard)"
dutylist["The Akh Afah Amphitheatre (Hard)"] = "The Akh Afah Amphitheatre (Hard)"
dutylist["The Dragon's Neck"] = "The Dragon's Neck"
dutylist["The Chrysalis"] = "The Chrysalis"
dutylist["Battle in the Big Keep"] = "Battle in the Big Keep"
dutylist["Urth's Fount"] = "Urth's Fount"
dutylist["The Minstrel's Ballad Ultima's Bane"] = "The Minstrel's Ballad: Ultima's Bane"
dutylist["The Howling Eye (Extreme)"] = "The Howling Eye (Extreme)"
dutylist["The Navel (Extreme)"] = "The Navel (Extreme)"
dutylist["The Bowl of Embers (Extreme)"] = "The Bowl of Embers (Extreme)"
dutylist["Thornmarch (Extreme)"] = "Thornmarch (Extreme)"
dutylist["The Whorleater (Extreme)"] = "The Whorleater (Extreme)"
dutylist["The Striking Tree (Extreme)"] = "The Striking Tree (Extreme)"
dutylist["The Akh Afah Amphitheatre (Extreme)"] = "The Akh Afah Amphitheatre (Extreme)"
dutylist["The Binding Coil of Bahamut - Turn 1"] = "The Binding Coil of Bahamut - Turn 1"
dutylist["The Binding Coil of Bahamut - Turn 2"] = "The Binding Coil of Bahamut - Turn 2"
dutylist["The Binding Coil of Bahamut - Turn 3"] = "The Binding Coil of Bahamut - Turn 3"
dutylist["The Binding Coil of Bahamut - Turn 4"] = "The Binding Coil of Bahamut - Turn 4"
dutylist["The Binding Coil of Bahamut - Turn 5"] = "The Binding Coil of Bahamut - Turn 5"
dutylist["The Second Coil of Bahamut - Turn 1"] = "The Second Coil of Bahamut - Turn 1"
dutylist["The Second Coil of Bahamut - Turn 2"] = "The Second Coil of Bahamut - Turn 2"
dutylist["The Second Coil of Bahamut - Turn 3"] = "The Second Coil of Bahamut - Turn 3"
dutylist["The Second Coil of Bahamut - Turn 4"] = "The Second Coil of Bahamut - Turn 4"
dutylist["The Second Coil of Bahamut (Savage) - Turn 1"] = "The Second Coil of Bahamut (Savage) - Turn 1"
dutylist["The Second Coil of Bahamut (Savage) - Turn 2"] = "The Second Coil of Bahamut (Savage) - Turn 2"
dutylist["The Second Coil of Bahamut (Savage) - Turn 3"] = "The Second Coil of Bahamut (Savage) - Turn 3"
dutylist["The Second Coil of Bahamut (Savage) - Turn 4"] = "The Second Coil of Bahamut (Savage) - Turn 4"
dutylist["The Final Coil of Bahamut - Turn 1"] = "The Final Coil of Bahamut - Turn 1"
dutylist["The Final Coil of Bahamut - Turn 2"] = "The Final Coil of Bahamut - Turn 2"
dutylist["The Final Coil of Bahamut - Turn 3"] = "The Final Coil of Bahamut - Turn 3"
dutylist["The Final Coil of Bahamut - Turn 4"] = "The Final Coil of Bahamut - Turn 4"
dutylist["The Labyrinth of the Ancients"] = "The Labyrinth of the Ancients"
dutylist["Syrcus Tower"] = "Syrcus Tower"
dutylist["The World of Darkness"] = "The World of Darkness"
dutylist["Basic Training: Enemy Parties"] = "Basic Training: Enemy Parties"
dutylist["Under the Armor"] = "Under the Armor"
dutylist["Basic Training: Enemy Strongholds"] = "Basic Training: Enemy Strongholds"
dutylist["Hero on the Half Shell"] = "Hero on the Half Shell"
dutylist["Pulling Poison Posies"] = "Pulling Poison Posies"
dutylist["Stinging Back"] = "Stinging Back"
dutylist["All's Well that Ends in the Well"] = "All's Well that Ends in the Well"
dutylist["Flicking Sticks and Taking Names"] = "Flicking Sticks and Taking Names"
dutylist["More than a Feeler"] = "More than a Feeler"
dutylist["Annoy the Void"] = "Annoy the Void"
dutylist["Shadow and Claw"] = "Shadow and Claw"
dutylist["Long Live the Queen"] = "Long Live the Queen"
dutylist["Ward Up"] = "Ward Up"
dutylist["Solemn Trinity"] = "Solemn Trinity"
dutylist["The Palaistra"] = "The Palaistra"
dutylist["The Volcanic Heart"] = "The Volcanic Heart"
dutylist["Cloud Nine"] = "Cloud Nine"
dutylist["The Clockwork Castletown"] = "The Clockwork Castletown"
dutylist["The Red Sands"] = "The Red Sands"
dutylist["The Bayside Battleground"] = "The Bayside Battleground"
dutylist["Archeia Harmonias"] = "Archeia Harmonias"
dutylist["The Dusk Vigil"] = "The Dusk Vigil"
dutylist["Sohm Al"] = "Sohm Al"
dutylist["The Aery"] = "The Aery"
dutylist["The Vault"] = "The Vault"
dutylist["The Great Gubal Library"] = "The Great Gubal Library"
dutylist["The Aetherochemical Research Facility"] = "The Aetherochemical Research Facility"
dutylist["Neverreap"] = "Neverreap"
dutylist["The Fractal Continuum"] = "The Fractal Continuum"
dutylist["Saint Mocianne's Arboretum"] = "Saint Mocianne's Arboretum"
dutylist["Pharos Sirius (Hard)"] = "Pharos Sirius (Hard)"
dutylist["The Antitower"] = "The Antitower"
dutylist["The Lost City of Amdapor (Hard)"] = "The Lost City of Amdapor (Hard)"
dutylist["Sohr Khai"] = "Sohr Khai"
dutylist["Hullbreaker Isle (Hard)"] = "Hullbreaker Isle (Hard)"
dutylist["Xelphatol"] = "Xelphatol"
dutylist["The Great Gubal Library (Hard)"] = "The Great Gubal Library (Hard)"
dutylist["Baelsar's Wall"] = "Baelsar's Wall"
dutylist["Sohm Al (Hard)"] = "Sohm Al (Hard)"
dutylist["Thok ast Thok (Hard)"] = "Thok ast Thok (Hard)"
dutylist["The Limitless Blue (Hard)"] = "The Limitless Blue (Hard)"
dutylist["The Singularity Reactor"] = "The Singularity Reactor"
dutylist["Containment Bay S1T7"] = "Containment Bay S1T7"
dutylist["The Final Steps of Faith"] = "The Final Steps of Faith"
dutylist["Containment Bay P1T6"] = "Containment Bay P1T6"
dutylist["Containment Bay Z1T9"] = "Containment Bay Z1T9"
dutylist["The Limitless Blue (Extreme)"] = "The Limitless Blue (Extreme)"
dutylist["Thok ast Thok (Extreme)"] = "Thok ast Thok (Extreme)"
dutylist["The Minstrel's Ballad Thordan's Reign"] = "The Minstrel's Ballad: Thordan's Reign"
dutylist["Containment Bay S1T7 (Extreme)"] = "Containment Bay S1T7 (Extreme)"
dutylist["The Minstrel's Ballad Nidhogg's Rage"] = "The Minstrel's Ballad: Nidhogg's Rage"
dutylist["Containment Bay P1T6 (Extreme)"] = "Containment Bay P1T6 (Extreme)"
dutylist["Containment Bay Z1T9 (Extreme)"] = "Containment Bay Z1T9 (Extreme)"
dutylist["Alexander - The Fist of the Father"] = "Alexander - The Fist of the Father"
dutylist["Alexander - The Cuff of the Father"] = "Alexander - The Cuff of the Father"
dutylist["Alexander - The Arm of the Father"] = "Alexander - The Arm of the Father"
dutylist["Alexander - The Burden of the Father"] = "Alexander - The Burden of the Father"
dutylist["Alexander - The Fist of the Son"] = "Alexander - The Fist of the Son"
dutylist["Alexander - The Cuff of the Son"] = "Alexander - The Cuff of the Son"
dutylist["Alexander - The Arm of the Son"] = "Alexander - The Arm of the Son"
dutylist["Alexander - The Burden of the Son"] = "Alexander - The Burden of the Son"
dutylist["Alexander - The Eyes of the Creator"] = "Alexander - The Eyes of the Creator"
dutylist["Alexander - The Breath of the Creator"] = "Alexander - The Breath of the Creator"
dutylist["Alexander - The Heart of the Creator"] = "Alexander - The Heart of the Creator"
dutylist["Alexander - The Soul of the Creator"] = "Alexander - The Soul of the Creator"
dutylist["Alexander - The Fist of the Father (Savage)"] = "Alexander - The Fist of the Father (Savage)"
dutylist["Alexander - The Cuff of the Father (Savage)"] = "Alexander - The Cuff of the Father (Savage)"
dutylist["Alexander - The Arm of the Father (Savage)"] = "Alexander - The Arm of the Father (Savage)"
dutylist["Alexander - The Burden of the Father (Savage)"] = "Alexander - The Burden of the Father (Savage)"
dutylist["Alexander - The Fist of the Son (Savage)"] = "Alexander - The Fist of the Son (Savage)"
dutylist["Alexander - The Cuff of the Son (Savage)"] = "Alexander - The Cuff of the Son (Savage)"
dutylist["Alexander - The Arm of the Son (Savage)"] = "Alexander - The Arm of the Son (Savage)"
dutylist["Alexander - The Burden of the Son (Savage)"] = "Alexander - The Burden of the Son (Savage)"
dutylist["Alexander - The Eyes of the Creator (Savage)"] = "Alexander - The Eyes of the Creator (Savage)"
dutylist["Alexander - The Breath of the Creator (Savage)"] = "Alexander - The Breath of the Creator (Savage)"
dutylist["Alexander - The Heart of the Creator (Savage)"] = "Alexander - The Heart of the Creator (Savage)"
dutylist["Alexander - The Soul of the Creator (Savage)"] = "Alexander - The Soul of the Creator (Savage)"
dutylist["The Void Ark"] = "The Void Ark"
dutylist["The Weeping City of Mhach"] = "The Weeping City of Mhach"
dutylist["Dun Scaith"] = "Dun Scaith"
dutylist["The Sirensong Sea"] = "The Sirensong Sea"
dutylist["Shisui of the Violet Tides"] = "Shisui of the Violet Tides"
dutylist["Bardam's Mettle"] = "Bardam's Mettle"
dutylist["Doma Castle"] = "Doma Castle"
dutylist["Castrum Abania"] = "Castrum Abania"
dutylist["Ala Mhigo"] = "Ala Mhigo"
dutylist["Kugane Castle"] = "Kugane Castle"
dutylist["The Temple of the Fist"] = "The Temple of the Fist"
dutylist["The Drowned City of Skalla"] = "The Drowned City of Skalla"
dutylist["Hells' Lid"] = "Hells' Lid"
dutylist["The Fractal Continuum (Hard)"] = "The Fractal Continuum (Hard)"
dutylist["The Swallow's Compass"] = "The Swallow's Compass"
dutylist["The Burn"] = "The Burn"
dutylist["Saint Mocianne's Arboretum (Hard)"] = "Saint Mocianne's Arboretum (Hard)"
dutylist["The Ghimlyt Dark"] = "The Ghimlyt Dark"
dutylist["The Pool of Tribute"] = "The Pool of Tribute"
dutylist["Emanation"] = "Emanation"
dutylist["The Royal Menagerie"] = "The Royal Menagerie"
dutylist["The Jade Stoa"] = "The Jade Stoa"
dutylist["Castrum Fluminis"] = "Castrum Fluminis"
dutylist["The Great Hunt"] = "The Great Hunt"
dutylist["Hells' Kier"] = "Hells' Kier"
dutylist["The Wreath of Snakes"] = "The Wreath of Snakes"
dutylist["Kugane Ohashi"] = "Kugane Ohashi"
dutylist["The Pool of Tribute (Extreme)"] = "The Pool of Tribute (Extreme)"
dutylist["Emanation (Extreme)"] = "Emanation (Extreme)"
dutylist["The Minstrel's Ballad Shinryu's Domain"] = "The Minstrel's Ballad: Shinryu's Domain"
dutylist["The Jade Stoa (Extreme)"] = "The Jade Stoa (Extreme)"
dutylist["The Minstrel's Ballad Tsukuyomi's Pain"] = "The Minstrel's Ballad: Tsukuyomi's Pain"
dutylist["The Great Hunt (Extreme)"] = "The Great Hunt (Extreme)"
dutylist["Hells' Kier (Extreme)"] = "Hells' Kier (Extreme)"
dutylist["The Wreath of Snakes (Extreme)"] = "The Wreath of Snakes (Extreme)"
dutylist["Deltascape V1.0"] = "Deltascape V1.0"
dutylist["Deltascape V2.0"] = "Deltascape V2.0"
dutylist["Deltascape V3.0"] = "Deltascape V3.0"
dutylist["Deltascape V4.0"] = "Deltascape V4.0"
dutylist["Sigmascape V1.0"] = "Sigmascape V1.0"
dutylist["Sigmascape V2.0"] = "Sigmascape V2.0"
dutylist["Sigmascape V3.0"] = "Sigmascape V3.0"
dutylist["Sigmascape V4.0"] = "Sigmascape V4.0"
dutylist["Alphascape V1.0"] = "Alphascape V1.0"
dutylist["Alphascape V2.0"] = "Alphascape V2.0"
dutylist["Alphascape V3.0"] = "Alphascape V3.0"
dutylist["Alphascape V4.0"] = "Alphascape V4.0"
dutylist["Deltascape V1.0 (Savage)"] = "Deltascape V1.0 (Savage)"
dutylist["Deltascape V2.0 (Savage)"] = "Deltascape V2.0 (Savage)"
dutylist["Deltascape V3.0 (Savage)"] = "Deltascape V3.0 (Savage)"
dutylist["Deltascape V4.0 (Savage)"] = "Deltascape V4.0 (Savage)"
dutylist["Sigmascape V1.0 (Savage)"] = "Sigmascape V1.0 (Savage)"
dutylist["Sigmascape V2.0 (Savage)"] = "Sigmascape V2.0 (Savage)"
dutylist["Sigmascape V3.0 (Savage)"] = "Sigmascape V3.0 (Savage)"
dutylist["Sigmascape V4.0 (Savage)"] = "Sigmascape V4.0 (Savage)"
dutylist["Alphascape V1.0 (Savage)"] = "Alphascape V1.0 (Savage)"
dutylist["Alphascape V2.0 (Savage)"] = "Alphascape V2.0 (Savage)"
dutylist["Alphascape V3.0 (Savage)"] = "Alphascape V3.0 (Savage)"
dutylist["Alphascape V4.0 (Savage)"] = "Alphascape V4.0 (Savage)"
dutylist["The Royal City of Rabanastre"] = "The Royal City of Rabanastre"
dutylist["The Ridorana Lighthouse"] = "The Ridorana Lighthouse"
dutylist["The Orbonne Monastery"] = "The Orbonne Monastery"
dutylist["Holminster Switch"] = "Holminster Switch"
dutylist["Dohn Mheg"] = "Dohn Mheg"
dutylist["The Qitana Ravel"] = "The Qitana Ravel"
dutylist["Malikah's Well"] = "Malikah's Well"
dutylist["Mt. Gulg"] = "Mt. Gulg"
dutylist["Amaurot"] = "Amaurot"
dutylist["The Twinning"] = "The Twinning"
dutylist["Akadaemia Anyder"] = "Akadaemia Anyder"
dutylist["The Grand Cosmos"] = "The Grand Cosmos"
dutylist["Anamnesis Anyder"] = "Anamnesis Anyder"
dutylist["The Heroes' Gauntlet"] = "The Heroes' Gauntlet"
dutylist["Matoya's Relict"] = "Matoya's Relict"
dutylist["Paglth'an"] = "Paglth'an"
dutylist["The Dancing Plague"] = "The Dancing Plague"
dutylist["The Crown of the Immaculate"] = "The Crown of the Immaculate"
dutylist["The Dying Gasp"] = "The Dying Gasp"
dutylist["Cinder Drift"] = "Cinder Drift"
dutylist["The Seat of Sacrifice"] = "The Seat of Sacrifice"
dutylist["Castrum Marinum"] = "Castrum Marinum"
dutylist["The Cloud Deck"] = "The Cloud Deck"
dutylist["The Dancing Plague (Extreme)"] = "The Dancing Plague (Extreme)"
dutylist["The Crown of the Immaculate (Extreme)"] = "The Crown of the Immaculate (Extreme)"
dutylist["The Minstrel's Ballad Hades's Elegy"] = "The Minstrel's Ballad: Hades's Elegy"
dutylist["Cinder Drift (Extreme)"] = "Cinder Drift (Extreme)"
dutylist["Memoria Misera (Extreme)"] = "Memoria Misera (Extreme)"
dutylist["The Seat of Sacrifice (Extreme)"] = "The Seat of Sacrifice (Extreme)"
dutylist["Castrum Marinum (Extreme)"] = "Castrum Marinum (Extreme)"
dutylist["The Cloud Deck (Extreme)"] = "The Cloud Deck (Extreme)"
dutylist["Eden's Gate Resurrection"] = "Eden's Gate: Resurrection"
dutylist["Eden's Gate Descent"] = "Eden's Gate: Descent"
dutylist["Eden's Gate Inundation"] = "Eden's Gate: Inundation"
dutylist["Eden's Gate Sepulture"] = "Eden's Gate: Sepulture"
dutylist["Eden's Verse Fulmination"] = "Eden's Verse: Fulmination"
dutylist["Eden's Verse Furor"] = "Eden's Verse: Furor"
dutylist["Eden's Verse Iconoclasm"] = "Eden's Verse: Iconoclasm"
dutylist["Eden's Verse Refulgence"] = "Eden's Verse: Refulgence"
dutylist["Eden's Promise Umbra"] = "Eden's Promise: Umbra"
dutylist["Eden's Promise Litany"] = "Eden's Promise: Litany"
dutylist["Eden's Promise Anamorphosis"] = "Eden's Promise: Anamorphosis"
dutylist["Eden's Promise Eternity"] = "Eden's Promise: Eternity"
dutylist["Eden's Gate Resurrection (Savage)"] = "Eden's Gate: Resurrection (Savage)"
dutylist["Eden's Gate Descent (Savage)"] = "Eden's Gate: Descent (Savage)"
dutylist["Eden's Gate Inundation (Savage)"] = "Eden's Gate: Inundation (Savage)"
dutylist["Eden's Gate Sepulture (Savage)"] = "Eden's Gate: Sepulture (Savage)"
dutylist["Eden's Verse Fulmination (Savage)"] = "Eden's Verse: Fulmination (Savage)"
dutylist["Eden's Verse Furor (Savage)"] = "Eden's Verse: Furor (Savage)"
dutylist["Eden's Verse Iconoclasm (Savage)"] = "Eden's Verse: Iconoclasm (Savage)"
dutylist["Eden's Verse Refulgence (Savage)"] = "Eden's Verse: Refulgence (Savage)"
dutylist["Eden's Promise Umbra (Savage)"] = "Eden's Promise: Umbra (Savage)"
dutylist["Eden's Promise Litany (Savage)"] = "Eden's Promise: Litany (Savage)"
dutylist["Eden's Promise Anamorphosis (Savage)"] = "Eden's Promise: Anamorphosis (Savage)"
dutylist["Eden's Promise Eternity (Savage)"] = "Eden's Promise: Eternity (Savage)"
dutylist["The Copied Factory"] = "The Copied Factory"
dutylist["The Puppets' Bunker"] = "The Puppets' Bunker"
dutylist["The Tower at Paradigm's Breach"] = "The Tower at Paradigm's Breach"
dutylist["The Battle of Castrum Lacus Litore"] = "The Battle of Castrum Lacus Litore"
dutylist["Delubrum Reginae"] = "Delubrum Reginae"
dutylist["The Dalriada"] = "The Dalriada"
dutylist["Kill It with Fire"] = "Kill It with Fire"
dutylist["The Baying of the Hound(s)"] = "The Baying of the Hound(s)"
dutylist["Vigil for the Lost"] = "Vigil for the Lost"
dutylist["Aces High"] = "Aces High"
dutylist["The Shadow of Death's Hand"] = "The Shadow of Death's Hand"
dutylist["The Final Furlong"] = "The Final Furlong"
dutylist["The Hunt for Red Choctober"] = "The Hunt for Red Choctober"
dutylist["Beast of Man"] = "Beast of Man"
dutylist["The Fires of War"] = "The Fires of War"
dutylist["Patriot Games"] = "Patriot Games"
dutylist["Trampled under Hoof"] = "Trampled under Hoof"
dutylist["And the Flames Went Higher"] = "And the Flames Went Higher"
dutylist["Metal Fox Chaos"] = "Metal Fox Chaos"
dutylist["Rise of the Robots"] = "Rise of the Robots"
dutylist["Where Strode the Behemoth"] = "Where Strode the Behemoth"
dutylist["On Serpents' Wings"] = "On Serpents' Wings"
dutylist["Feeling the Burn"] = "Feeling the Burn"
dutylist["The Broken Blade"] = "The Broken Blade"
dutylist["From Beyond the Grave"] = "From Beyond the Grave"
dutylist["With Diremite and Main"] = "With Diremite and Main"
dutylist["Here Comes the Cavalry"] = "Here Comes the Cavalry"
dutylist["Head of the Snake"] = "Head of the Snake"
dutylist["There Would Be Blood"] = "There Would Be Blood"
dutylist["Never Cry Wolf"] = "Never Cry Wolf"
dutylist["Time to Burn"] = "Time to Burn"
dutylist["Lean, Mean, Magitek Machines"] = "Lean, Mean, Magitek Machines"
dutylist["Worn to a Shadow"] = "Worn to a Shadow"
dutylist["A Familiar Face"] = "A Familiar Face"
dutylist["Looks to Die For"] = "Looks to Die For"
dutylist["Taking the Lyon's Share"] = "Taking the Lyon's Share"

dutylist["The Tower of Zot"] = "The Tower of Zot"
dutylist["The Tower of Babil"] = "The Tower of Babil"
dutylist["Vanaspati"] = "Vanaspati"
dutylist["Ktisis Hyperboreia"] = "Ktisis Hyperboreia"
dutylist["The Aitiascope"] = "The Aitiascope"
dutylist["The Dead Ends"] = "The Dead Ends"
dutylist["Smileton"] = "Smileton"
dutylist["The Stigma Dreamscape"] = "The Stigma Dreamscape"
dutylist["Alzadaal's Legacy"] = "Alzadaal's Legacy"
dutylist["The Fell Court of Troia"] = "The Fell Court of Troia"
dutylist["Lapis Manalis"] = "Lapis Manalis"
dutylist["The Aetherfont"] = "The Aetherfont"
dutylist["The Lunar Subterrane"] = "The Lunar Subterrane"
dutylist["The Dark Inside"] = "The Dark Inside"
dutylist["The Mothercrystal"] = "The Mothercrystal"
dutylist["The Final Day"] = "The Final Day"
dutylist["Storm's Crown"] = "Storm's Crown"
dutylist["Mount Ordeals"] = "Mount Ordeals"
dutylist["The Voidcast Dais"] = "The Voidcast Dais"
dutylist["The Abyssal Fracture"] = "The Abyssal Fracture"
dutylist["The Gilded Araya"] = "The Gilded Araya"
dutylist["The Minstrel's Ballad Zodiark's Fall"] = "The Minstrel's Ballad: Zodiark's Fall"
dutylist["The Minstrel's Ballad Hydaelyn's Call"] = "The Minstrel's Ballad: Hydaelyn's Call"
dutylist["The Minstrel's Ballad Endsinger's Aria"] = "The Minstrel's Ballad: Endsinger's Aria"
dutylist["Storm's Crown (Extreme)"] = "Storm's Crown (Extreme)"
dutylist["Mount Ordeals (Extreme)"] = "Mount Ordeals (Extreme)"
dutylist["The Voidcast Dais (Extreme)"] = "The Voidcast Dais (Extreme)"
dutylist["The Abyssal Fracture (Extreme)"] = "The Abyssal Fracture (Extreme)"
dutylist["The Sil'dihn Subterrane"] = "The Sil'dihn Subterrane"
dutylist["Mount Rokkon"] = "Mount Rokkon"
dutylist["Aloalo Island"] = "Aloalo Island"
dutylist["Asphodelos The First Circle"] = "Asphodelos: The First Circle"
dutylist["Asphodelos The Second Circle"] = "Asphodelos: The Second Circle"
dutylist["Asphodelos The Third Circle"] = "Asphodelos: The Third Circle"
dutylist["Asphodelos The Fourth Circle"] = "Asphodelos: The Fourth Circle"
dutylist["Abyssos The Fifth Circle"] = "Abyssos: The Fifth Circle"
dutylist["Abyssos The Sixth Circle"] = "Abyssos: The Sixth Circle"
dutylist["Abyssos The Seventh Circle"] = "Abyssos: The Seventh Circle"
dutylist["Abyssos The Eighth Circle"] = "Abyssos: The Eighth Circle"
dutylist["Anabaseios The Ninth Circle"] = "Anabaseios: The Ninth Circle"
dutylist["Anabaseios The Tenth Circle"] = "Anabaseios: The Tenth Circle"
dutylist["Anabaseios The Eleventh Circle"] = "Anabaseios: The Eleventh Circle"
dutylist["Anabaseios The Twelfth Circle"] = "Anabaseios: The Twelfth Circle"
dutylist["Asphodelos The First Circle (Savage)"] = "Asphodelos: The First Circle (Savage)"
dutylist["Asphodelos The Second Circle (Savage)"] = "Asphodelos: The Second Circle (Savage)"
dutylist["Asphodelos The Third Circle (Savage)"] = "Asphodelos: The Third Circle (Savage)"
dutylist["Asphodelos The Fourth Circle (Savage)"] = "Asphodelos: The Fourth Circle (Savage)"
dutylist["Abyssos The Fifth Circle (Savage)"] = "Abyssos: The Fifth Circle (Savage)"
dutylist["Abyssos The Sixth Circle (Savage)"] = "Abyssos: The Sixth Circle (Savage)"
dutylist["Abyssos The Seventh Circle (Savage)"] = "Abyssos: The Seventh Circle (Savage)"
dutylist["Abyssos The Eighth Circle (Savage)"] = "Abyssos: The Eighth Circle (Savage)"
dutylist["Anabaseios The Ninth Circle (Savage)"] = "Anabaseios: The Ninth Circle (Savage)"
dutylist["Anabaseios The Tenth Circle (Savage)"] = "Anabaseios: The Tenth Circle (Savage)"
dutylist["Anabaseios The Eleventh Circle (Savage)"] = "Anabaseios: The Eleventh Circle (Savage)"
dutylist["Anabaseios The Twelfth Circle (Savage)"] = "Anabaseios: The Twelfth Circle (Savage)"
dutylist["Aglaia"] = "Aglaia"
dutylist["Euphrosyne"] = "Euphrosyne"
dutylist["Thaleia"] = "Thaleia"
dutylist["Ihuykatumu"] = "Ihuykatumu"
dutylist["Worqor Zormor"] = "Worqor Zormor"
dutylist["The Skydeep Cenote"] = "The Skydeep Cenote"
dutylist["Vanguard"] = "Vanguard"
dutylist["Origenics"] = "Origenics"
dutylist["Alexandria"] = "Alexandria"
dutylist["Tender Valley"] = "Tender Valley"
dutylist["The Strayborough Deadwalk"] = "The Strayborough Deadwalk"
dutylist["Yuweyawata Field Station"] = "Yuweyawata Field Station"
dutylist["The Underkeep"] = "The Underkeep"
dutylist["The Meso Terminal"] = "The Meso Terminal"
dutylist["Mistwake"] = "Mistwake"
dutylist["The Merchant's Tale"] = "The Merchant's Tale"
dutylist["The Clyteum"] = "The Clyteum"
dutylist["Worqor Lar Dor"] = "Worqor Lar Dor"
dutylist["Everkeep"] = "Everkeep"
dutylist["The Interphos"] = "The Interphos"
dutylist["Recollection"] = "Recollection"
dutylist["The Ageless Necropolis"] = "The Ageless Necropolis"
dutylist["The Windward Wilds"] = "The Windward Wilds"
dutylist["Hell on Rails"] = "Hell on Rails"
dutylist["The Unmaking"] = "The Unmaking"
dutylist["Worqor Lar Dor (Extreme)"] = "Worqor Lar Dor (Extreme)"
dutylist["Everkeep (Extreme)"] = "Everkeep (Extreme)"
dutylist["The Minstrel's Ballad Sphene's Burden"] = "The Minstrel's Ballad: Sphene's Burden"
dutylist["Recollection (Extreme)"] = "Recollection (Extreme)"
dutylist["The Minstrel's Ballad Necron's Embrace"] = "The Minstrel's Ballad: Necron's Embrace"
dutylist["The Windward Wilds (Extreme)"] = "The Windward Wilds (Extreme)"
dutylist["Hell on Rails (Extreme)"] = "Hell on Rails (Extreme)"
dutylist["The Unmaking (Extreme)"] = "The Unmaking (Extreme)"
dutylist["AAC Light-heavyweight M1"] = "AAC Light-heavyweight M1"
dutylist["AAC Light-heavyweight M2"] = "AAC Light-heavyweight M2"
dutylist["AAC Light-heavyweight M3"] = "AAC Light-heavyweight M3"
dutylist["AAC Light-heavyweight M4"] = "AAC Light-heavyweight M4"
dutylist["AAC Cruiserweight M1"] = "AAC Cruiserweight M1"
dutylist["AAC Cruiserweight M2"] = "AAC Cruiserweight M2"
dutylist["AAC Cruiserweight M3"] = "AAC Cruiserweight M3"
dutylist["AAC Cruiserweight M4"] = "AAC Cruiserweight M4"
dutylist["AAC Heavyweight M1"] = "AAC Heavyweight M1"
dutylist["AAC Heavyweight M2"] = "AAC Heavyweight M2"
dutylist["AAC Heavyweight M3"] = "AAC Heavyweight M3"
dutylist["AAC Heavyweight M4"] = "AAC Heavyweight M4"
dutylist["AAC Light-heavyweight M1 (Savage)"] = "AAC Light-heavyweight M1 (Savage)"
dutylist["AAC Light-heavyweight M2 (Savage)"] = "AAC Light-heavyweight M2 (Savage)"
dutylist["AAC Light-heavyweight M3 (Savage)"] = "AAC Light-heavyweight M3 (Savage)"
dutylist["AAC Light-heavyweight M4 (Savage)"] = "AAC Light-heavyweight M4 (Savage)"
dutylist["AAC Cruiserweight M1 (Savage)"] = "AAC Cruiserweight M1 (Savage)"
dutylist["AAC Cruiserweight M2 (Savage)"] = "AAC Cruiserweight M2 (Savage)"
dutylist["AAC Cruiserweight M3 (Savage)"] = "AAC Cruiserweight M3 (Savage)"
dutylist["AAC Cruiserweight M4 (Savage)"] = "AAC Cruiserweight M4 (Savage)"
dutylist["AAC Heavyweight M1 (Savage)"] = "AAC Heavyweight M1 (Savage)"
dutylist["AAC Heavyweight M2 (Savage)"] = "AAC Heavyweight M2 (Savage)"
dutylist["AAC Heavyweight M3 (Savage)"] = "AAC Heavyweight M3 (Savage)"
dutylist["AAC Heavyweight M4 (Savage)"] = "AAC Heavyweight M4 (Savage)"
dutylist["Jeuno The First Walk"] = "Jeuno: The First Walk"
dutylist["San d'Oria The Second Walk"] = "San d'Oria: The Second Walk"
dutylist["Windurst The Third Walk"] = "Windurst: The Third Walk"
dutylist["Scourge of the Mind"] = "Scourge of the Mind"
dutylist["The Black Regiment"] = "The Black Regiment"
dutylist["The Unbridled"] = "The Unbridled"
dutylist["Crawling Death"] = "Crawling Death"
dutylist["Calamity Bound"] = "Calamity Bound"
dutylist["Trial by Claw"] = "Trial by Claw"
dutylist["From Times Bygone"] = "From Times Bygone"
dutylist["Company of Stone"] = "Company of Stone"
dutylist["Shark Attack"] = "Shark Attack"
dutylist["On the Hunt"] = "On the Hunt"
dutylist["With Extreme Prejudice"] = "With Extreme Prejudice"
dutylist["Noise Complaint"] = "Noise Complaint"
dutylist["Cursed Concern"] = "Cursed Concern"
dutylist["Eternal Watch"] = "Eternal Watch"
dutylist["Flame of Dusk"] = "Flame of Dusk"
dutylist["The Forked Tower: Blood"] = "The Forked Tower: Blood"


















































































