fatelist["On the Lamb"] = 3
fatelist["Taking It to the Streams"] = 4
fatelist["Overnight Migration"] = 5
fatelist["Yellow-bellied Greenbacks"] = 5
fatelist["Thwack-a-Mole"] = 6
fatelist["Crying over Spilled Salt"] = 7
fatelist["Hello Work"] = 7
fatelist["Menuis at Work"] = 8
fatelist["The Orange Boxes"] = 9
fatelist["Shearing is Caring"] = 10
fatelist["Sister Crustacean"] = 12
fatelist["Go Wespe"] = 13
fatelist["A Mad Mad Mad Sergeant"] = 14
fatelist["The Boy Who Cried Jackal"] = 14
fatelist["The Truth Is out There"] = 14
fatelist["I Melt with You"] = 3
fatelist["You Call that a Toad"] = 4
fatelist["Fight the Flower"] = 5
fatelist["Caving In"] = 7
fatelist["Man of the Flour"] = 8
fatelist["Enter Beastman"] = 9
fatelist["One Pickman Enters"] = 9
fatelist["In the Name of Love"] = 10
fatelist["Under the Bridge"] = 10
fatelist["Away in a Bilge Hold"] = 11
fatelist["Don't Drink the Water"] = 12
fatelist["One Prince"] = 13
fatelist["Careless Whiskers"] = 30
fatelist["Crab and Go"] = 30
fatelist["Just a Matter of Rut"] = 31
fatelist["9 to 5"] = 32
fatelist["Cliff Hanger"] = 32
fatelist["Finding Wine"] = 32
fatelist["It's Not Lupus"] = 32
fatelist["Jewels of the Isle"] = 32
fatelist["Say My Name"] = 32
fatelist["The Pelican Briefing"] = 32
fatelist["The Thirst"] = 32
fatelist["Consigned Sealed and Undelivered"] = 33
fatelist["Follow the Light"] = 33
fatelist["Ho Ho Ho"] = 33
fatelist["Long Way Home"] = 33
fatelist["No Lip"] = 33
fatelist["Sweeter than Honey"] = 33
fatelist["Them"] = 33
fatelist["Thrill of the Hunt"] = 33
fatelist["Closing Time"] = 34
fatelist["Barometz Soup"] = 10
fatelist["Shredding Wheat"] = 10
fatelist["Tender Buttons"] = 12
fatelist["The Last Straw"] = 12
fatelist["(I Just) Died in Six Arms Tonight"] = 13
fatelist["Between Aurochs"] = 15
fatelist["Goblin Chain"] = 15
fatelist["Absolutely Positively"] = 16
fatelist["In the Sac"] = 16
fatelist["Don't Call Him a Fishback"] = 17
fatelist["Letters from Tidegate"] = 17
fatelist["Iron Contra Affair"] = 18
fatelist["Tryp Fantastic"] = 18
fatelist["Dead Man's Rest"] = 40
fatelist["The King's Justice"] = 40
fatelist["Breaching North Tidegate"] = 44
fatelist["Gauging North Tidegate"] = 44
fatelist["Sharknado"] = 44
fatelist["Breaching South Tidegate"] = 45
fatelist["Gauging South Tidegate"] = 45
fatelist["Tail of a Whale"] = 46
fatelist["Watch Your Tongue"] = 48
fatelist["Making Waves"] = 49
fatelist["Poor Maid's Mess"] = 20
fatelist["Poor Maid's Misfortune"] = 20
fatelist["Poor Maid's Mishap"] = 20
fatelist["Giant Enemy Crab"] = 21
fatelist["Simurgh Is the Word"] = 23
fatelist["The Road More Traveled"] = 30
fatelist["Truth in Faerie Tales"] = 30
fatelist["Nine-ilm Snails"] = 31
fatelist["Shell Shocked"] = 31
fatelist["Hop Skip and a Jump"] = 33
fatelist["Peeping Ja"] = 33
fatelist["Surprise"] = 34
fatelist["Peryton Perhaps"] = 30
fatelist["By a Whisker"] = 34
fatelist["I'm a Rock Not a Number"] = 34
fatelist["Overlooking the Obvious"] = 34
fatelist["Restless in O'Ghomoro"] = 34
fatelist["The Only Way Is Up"] = 34
fatelist["When the Coeurl's Away"] = 34
fatelist["Fire in the Hole"] = 41
fatelist["Make it Rain"] = 41
fatelist["Schism"] = 41
fatelist["The Miner in the Mirror"] = 44
fatelist["Making the Rounds"] = 47
fatelist["Stopping the Shakes"] = 47
fatelist["Full Metal Alchemist"] = 49
fatelist["One Enchanted Eve"] = 4
fatelist["Clever Girls"] = 5
fatelist["Training Day"] = 5
fatelist["Lady Killer"] = 7
fatelist["A Mother Scorned"] = 8
fatelist["Something in the Water"] = 8
fatelist["Alux of the Draw"] = 9
fatelist["Leader of the Pack"] = 9
fatelist["Lethe on My Mind"] = 10
fatelist["Spirithold Run"] = 10
fatelist["Love is in the Air"] = 11
fatelist["The Sting"] = 11
fatelist["Sleep Tight"] = 12
fatelist["Bleeding Green"] = 13
fatelist["There's Something About Lou"] = 14
fatelist["What's Your Poison"] = 30
fatelist["My Baby Green"] = 31
fatelist["Revenant Things"] = 31
fatelist["The Lindwurm Has Turned"] = 31
fatelist["If I Only Had a Soul"] = 33
fatelist["Asipatra Attacks"] = 34
fatelist["In Spite of It All"] = 43
fatelist["Steel Reign"] = 50
fatelist["Carrion Baggage"] = 11
fatelist["Now I See Bees I Won"] = 11
fatelist["Royal Rumble"] = 16
fatelist["Stopping the Spread"] = 17
fatelist["Ivy League"] = 19
fatelist["Jack of All Trades"] = 19
fatelist["Lazy for You"] = 20
fatelist["Protecting the Patch"] = 20
fatelist["What Have You Done for Mead Lately"] = 21
fatelist["Thunderstruck"] = 23
fatelist["All Vine and No Popotoes"] = 40
fatelist["Collecting Keepsakes"] = 40
fatelist["A Wrench in the Works"] = 42
fatelist["The Enemy of My Enemy"] = 42
fatelist["The Enmity of My Enemy"] = 42
fatelist["The Squirrel Trapper's Wife"] = 43
fatelist["Below His Station"] = 44
fatelist["Got Milkroot"] = 46
fatelist["Breaking Dawn"] = 47
fatelist["Bush Blade"] = 47
fatelist["Everything's Better"] = 49
fatelist["Handful of Dreams"] = 49
fatelist["The Gale that Rocks the Cradle"] = 49
fatelist["What a Boar"] = 49
fatelist["Stag Parting"] = 21
fatelist["Another Round"] = 22
fatelist["Kickin' it with the Kedtraps"] = 22
fatelist["To Whom the Toll Goes"] = 22
fatelist["The Hunted"] = 23
fatelist["Conspiracy Theory"] = 24
fatelist["The Negotiators"] = 28
fatelist["Hide and Seek"] = 29
fatelist["Robbin' Goblins"] = 29
fatelist["The Coeurl King"] = 29
fatelist["To Train a Tortoise"] = 30
fatelist["Fate is a Fecal Mistress"] = 31
fatelist["A Tale of Two-tails"] = 32
fatelist["Breaching the Hive"] = 32
fatelist["Clearing the Hive"] = 32
fatelist["Defending the Hive"] = 32
fatelist["Keeping the Hive"] = 32
fatelist["Rogue on the Water"] = 33
fatelist["Eft for Dead"] = 34
fatelist["What Gored Before"] = 46
fatelist["Breaking Bud"] = 3
fatelist["Dschubba Snacks"] = 3
fatelist["No Birds Allowed"] = 5
fatelist["The Magical Fruit"] = 7
fatelist["Micromanaging"] = 8
fatelist["The Big Issue"] = 25
fatelist["Hare Today"] = 27
fatelist["It Ziz What It Is"] = 27
fatelist["That Which Binds Us"] = 28
fatelist["Waiting for a Moon to Fall"] = 28
fatelist["Don't Disturb This Grove"] = 37
fatelist["Smells Like Tree Spirit"] = 37
fatelist["Air Supply"] = 47
fatelist["Rude Awakening"] = 48
fatelist["Let them Eat Cactus"] = 5
fatelist["Like an Eft out of Water"] = 5
fatelist["Something to Prove"] = 5
fatelist["Survivor Rats"] = 6
fatelist["A Warm Welcome"] = 7
fatelist["Big Time"] = 7
fatelist["Wrecked Rats"] = 7
fatelist["Cracked"] = 9
fatelist["For the Queen"] = 9
fatelist["A Few Arrows Short of a Quiver"] = 11
fatelist["Leaving the Nest"] = 12
fatelist["Cold-blooded"] = 14
fatelist["Orobon Part Two The Spawning"] = 14
fatelist["A Matter of Rust"] = 5
fatelist["Needles to Slay"] = 5
fatelist["Things that Make You Go Home"] = 6
fatelist["Deface the Facts"] = 8
fatelist["Please Hammers Don't Hurt Them"] = 8
fatelist["The Cores"] = 8
fatelist["Doomed"] = 9
fatelist["The Villain"] = 9
fatelist["Copied Peistes"] = 10
fatelist["Dog Eat Dog"] = 10
fatelist["Pound for Pound"] = 10
fatelist["Bigger Fish to Fry"] = 13
fatelist["Bubble Trouble"] = 13
fatelist["Staying Dead"] = 20
fatelist["There Might Be Giants"] = 21
fatelist["He's Got Legs"] = 22
fatelist["Tripped up by the Fruit of Another"] = 22
fatelist["Juggernaut Down"] = 23
fatelist["License to Quill"] = 15
fatelist["Almost Paradise"] = 17
fatelist["Bazaar Blood Triangle"] = 17
fatelist["Deep in the Heart of Sagolii"] = 17
fatelist["Grim Undertakings"] = 17
fatelist["Simple Minds"] = 17
fatelist["Bad Camp"] = 18
fatelist["Westward Bound"] = 18
fatelist["Men Who See Goats"] = 19
fatelist["Attack on Highbridge Act I"] = 26
fatelist["Attack on Highbridge Act II"] = 26
fatelist["Attack on Highbridge Act III"] = 26
fatelist["Attack on Highbridge Denouement"] = 26
fatelist["Attack on Highbridge Prelude"] = 26
fatelist["Desert Rose"] = 26
fatelist["Manifest Destiny"] = 27
fatelist["Spare the Hair"] = 29
fatelist["A Man Rides Through"] = 40
fatelist["Bad Hair Day"] = 42
fatelist["Quartz Coupling"] = 42
fatelist["The Big Bagoly Theory"] = 42
fatelist["Downwind"] = 25
fatelist["Run Like a Flame"] = 26
fatelist["The Corpse Bribe"] = 27
fatelist["Adventures in Throat Slitting"] = 28
fatelist["Bump and Grind"] = 28
fatelist["Harder Bigger Faster Stronger"] = 28
fatelist["Soul Man"] = 29
fatelist["Children of the Sands"] = 31
fatelist["Fish out of Water"] = 31
fatelist["Blood Augur Hex Magicks"] = 32
fatelist["From Point A"] = 32
fatelist["Revenge of the Worms"] = 32
fatelist["Heroes of the 2nd"] = 45
fatelist["Taken"] = 45
fatelist["Bigger than Life"] = 46
fatelist["Book of Pride"] = 46
fatelist["Call Me Mayhaps"] = 46
fatelist["Fallen Corpses Writhe in Style"] = 46
fatelist["Full of Rigor Mortis"] = 46
fatelist["Tempered Tempered"] = 46
fatelist["An Inconvenient Truth"] = 48
fatelist["Diamond in the Rough"] = 48
fatelist["Future Shock"] = 48
fatelist["He's a Firestarter"] = 48
fatelist["Gyve Talk"] = 49
fatelist["Hunters and the Hunted"] = 49
fatelist["Quenching the Flame"] = 49
fatelist["Return to Cinder"] = 49
fatelist["Spark off the Bench"] = 49
fatelist["Boom Goes the Ceruleum"] = 49
fatelist["Core Blimey"] = 49
fatelist["Dark Devices The Bait"] = 49
fatelist["Dark Devices The End"] = 49
fatelist["Dark Devices The Plea"] = 49
fatelist["Dark Devices The Switch"] = 49
fatelist["East Meets Worst"] = 49
fatelist["Go Go Gorgimera"] = 49
fatelist["Just a Sip"] = 49
fatelist["Knock on Steel"] = 49
fatelist["Reverse Engineering"] = 49
fatelist["The Ceruleum Road"] = 49
fatelist["The Red Baron"] = 49
fatelist["Twinkle Twinkle Little Trap"] = 49
fatelist["Under the Nails"] = 49
fatelist["With One Eye Open"] = 49
fatelist["A Log Up"] = 35
fatelist["Gavial"] = 35
fatelist["Twelve Ilms of Snow"] = 35
fatelist["Baa Baa Black Sheep"] = 36
fatelist["Croc-y Road"] = 36
fatelist["Whiteout"] = 36
fatelist["Wish Upon a Star"] = 36
fatelist["A Fire in the Distance"] = 37
fatelist["Coming to a Head"] = 37
fatelist["Simply Red"] = 38
fatelist["Spring Forward Fall Back"] = 38
fatelist["Svara's Fall"] = 38
fatelist["Svara's Fear"] = 38
fatelist["Svara's Flight"] = 38
fatelist["Svara's Fury"] = 38
fatelist["The Grey"] = 38
fatelist["A Freeze Is Coming"] = 39
fatelist["Bellyful"] = 39
fatelist["Judge Jury and Executioner"] = 39
fatelist["Roc of Ages"] = 39
fatelist["The Eyes Have It"] = 39
fatelist["Front and Center"] = 40
fatelist["Giant Seps"] = 40
fatelist["If This Wall Could Talk"] = 40
fatelist["Riddle Me This"] = 40
fatelist["The Taste of Fear"] = 40
fatelist["In the Saint's Wake"] = 45
fatelist["Tower of Power"] = 45
fatelist["The Bigger They Are"] = 46
fatelist["Turn Off Your Hearthlight"] = 47
fatelist["What's On Your Mind"] = 47
fatelist["Does Anyone Hear It"] = 48
fatelist["Inspector Hatchet"] = 49
fatelist["The Four Winds"] = 49
fatelist["The Storm Caller"] = 49
fatelist["Behold Now Behemoth"] = 50
fatelist["He Taketh It with His Eyes"] = 50
fatelist["A Dung Deal"] = 50
fatelist["Apparent Trap"] = 50
fatelist["Dawn of the Mylodons"] = 50
fatelist["Don of the Mylodons"] = 50
fatelist["Eye in the Sky"] = 50
fatelist["Follow the Sleet"] = 50
fatelist["Land of the Freeze"] = 50
fatelist["No Ifs Ands or Butts"] = 50
fatelist["Null and Void"] = 50
fatelist["One Whiskey One Goat One Spear"] = 50
fatelist["Panic Rheum"] = 50
fatelist["Run Riders Run"] = 50
fatelist["Sugar Sugar"] = 50
fatelist["What You See Is What You Get"] = 50
fatelist["Abominable Me"] = 51
fatelist["Dishonored"] = 51
fatelist["In Command"] = 51
fatelist["Pico de Gallows"] = 51
fatelist["Requiem for a Dragon"] = 51
fatelist["Sick Pack"] = 51
fatelist["The Polar Express"] = 51
fatelist["True Convictions"] = 51
fatelist["Unsilent Vigil"] = 51
fatelist["We Fought a Dzu"] = 51
fatelist["A Stihi Situation"] = 56
fatelist["Sphenopalatine Ganglioneuralgia"] = 56
fatelist["Good to Be Bud"] = 44
fatelist["Mud About You"] = 44
fatelist["V for Vinedetta"] = 44
fatelist["Among Giants"] = 45
fatelist["Black and Nburu"] = 45
fatelist["The Prodigal Son"] = 45
fatelist["Toll Collector"] = 45
fatelist["Another Day Another Demon"] = 46
fatelist["Gone with the Shadow"] = 46
fatelist["Home Is Where the Horn Is"] = 46
fatelist["One Giant Leap"] = 46
fatelist["Standing Guard"] = 46
fatelist["That's What Adventurers Are For"] = 46
fatelist["Another Notch on the Torch"] = 48
fatelist["A Long Way Down"] = 50
fatelist["Anzu Trois"] = 50
fatelist["Food Fight"] = 50
fatelist["Leech the Sky"] = 50
fatelist["Mint Condition"] = 50
fatelist["One Turned Over the Cloudkin's Nest"] = 50
fatelist["Saved the Nests for Last"] = 50
fatelist["This Is How We Gundu"] = 50
fatelist["Youth Must Be Severed"] = 50
fatelist["Bones"] = 57
fatelist["Come to My Window"] = 57
fatelist["Hearts Like Steel Fists Like Thunder"] = 57
fatelist["Leather and Mace"] = 57
fatelist["Obey their Thirst"] = 57
fatelist["On Dangerous Ground"] = 57
fatelist["The Fugitive"] = 57
fatelist["Zuns on the Run"] = 57
fatelist["A Disturbing Lack of Faith"] = 59
fatelist["A Dream Perchance to Eat"] = 59
fatelist["Bismarcking Time"] = 59
fatelist["Guano a Mano"] = 59
fatelist["Let There Be Acolytes"] = 59
fatelist["Rebel Yehl"] = 59
fatelist["The Sound of Madness"] = 59
fatelist["You Eat What You Aren't"] = 59
fatelist["A Bug's Death"] = 59
fatelist["A Room Without Books"] = 59
fatelist["Curiously Strong Things"] = 59
fatelist["Do Spinners Dream of Electric Rooks"] = 59
fatelist["Harvest Moon"] = 59
fatelist["Life of Brain"] = 59
fatelist["No Greater Goryshche"] = 59
fatelist["Out of Sight Out of Mind"] = 59
fatelist["Pet Smart"] = 59
fatelist["Phi Slamma Gamma East"] = 59
fatelist["Phi Slamma Gamma South"] = 59
fatelist["Phi Slamma Gamma West"] = 59
fatelist["Prey Online"] = 59
fatelist["Put the Knives Down"] = 59
fatelist["Rampant Speculation"] = 59
fatelist["Scared Sylla"] = 59
fatelist["Still Ticking"] = 59
fatelist["The Late Escape"] = 59
fatelist["The Monster Mass"] = 59
fatelist["The Mystery Machine"] = 59
fatelist["The Root of Evil"] = 59
fatelist["Yak it Up"] = 59
fatelist["Bear Apparent"] = 52
fatelist["Birds of a Feather"] = 52
fatelist["By the Horns"] = 52
fatelist["Dead Meat"] = 52
fatelist["Drone Under"] = 52
fatelist["Glawackus On Glawackus Off"] = 52
fatelist["Ladies First"] = 52
fatelist["Long Live the Coeurl"] = 52
fatelist["Nothing but the Truth"] = 52
fatelist["Run Run Away"] = 52
fatelist["The Migas Touch"] = 52
fatelist["The Rite Stuff"] = 52
fatelist["The Whole Truth"] = 52
fatelist["Who's the Moss"] = 52
fatelist["Cerf's Up"] = 53
fatelist["El Miacid"] = 53
fatelist["Elephant in the Brume"] = 53
fatelist["Hearing Voices"] = 53
fatelist["Special Tarasque Force"] = 53
fatelist["Stamp the Yard"] = 53
fatelist["The Mourning After"] = 53
fatelist["Coeurls Chase Boys"] = 57
fatelist["Come to My Arms"] = 57
fatelist["Ware the Maiden Fair"] = 57
fatelist["Coeurls Chase Boys Chase Coeurls"] = 60
fatelist["Aevis Has Left the Building"] = 54
fatelist["Ain't Misbehaving"] = 54
fatelist["Asah I Came I Conquered"] = 54
fatelist["Corporal Pomishment"] = 54
fatelist["End of the Rainbow"] = 54
fatelist["Glycon Air"] = 54
fatelist["How to Cane Your Dragon"] = 54
fatelist["It's the Moogle Reinvented"] = 54
fatelist["Mogicide"] = 54
fatelist["Say it Tulihand"] = 54
fatelist["Sprite Club"] = 54
fatelist["Supper Time"] = 54
fatelist["The Nuts"] = 54
fatelist["Vouivre Believre"] = 54
fatelist["Waugyl Waugyl Waugyl"] = 54
fatelist["Wave Good-bye"] = 54
fatelist["Whole Food"] = 54
fatelist["Coin Toss"] = 55
fatelist["Darkscale Descendeth"] = 55
fatelist["Darkscale Devoureth"] = 55
fatelist["Darkscale Disappeareth"] = 55
fatelist["From Dusk Till Gone"] = 55
fatelist["Infamous"] = 55
fatelist["Rastaban Vibration"] = 55
fatelist["Treehouse of the Spirits"] = 55
fatelist["Waiting for Fjalar to Stall"] = 55
fatelist["As the World Burns"] = 56
fatelist["Don't Know Wyvern"] = 56
fatelist["Vedrfolnir Devoteth"] = 56
fatelist["Dobharch Did It for the Best"] = 58
fatelist["Feed Me See More"] = 58
fatelist["Gets the Red Out"] = 58
fatelist["Infant Vangob"] = 58
fatelist["Metal Gears Revengeance"] = 58
fatelist["Metal Gears Revengeance 2"] = 58
fatelist["Metal Gears Rising"] = 58
fatelist["Olympus Has Pollen"] = 58
fatelist["On Melancholic Hill"] = 58
fatelist["Out of the Woodwork"] = 58
fatelist["Pop Goes the Whizzle"] = 58
fatelist["Ratel and Hum"] = 58
fatelist["Revenge of the Vengeful Revengeance"] = 58
fatelist["Silkworm"] = 58
fatelist["Sun Bear Sun Bear What Do You Eat"] = 58
fatelist["Tarantula Hawk Pro Stinger"] = 58
fatelist["The Bear Up There"] = 58
fatelist["The Birds and the Bears"] = 58
fatelist["Tome Raider"] = 58
fatelist["Toss 'Em Back"] = 58
fatelist["Wild Wilde Death"] = 58
fatelist["Cockatrice Block"] = 59
fatelist["Come Shells or High Water"] = 59
fatelist["Frog Days of Summer"] = 59
fatelist["How Do You Feed a Hungry Manlike Monster"] = 59
fatelist["Makes the Very Best...Nests"] = 59
fatelist["Morbol Man"] = 59
fatelist["Poroggo Stuck"] = 59
fatelist["Toad Alone"] = 59
fatelist["Bold This Way"] = 60
fatelist["Death Beckons"] = 60
fatelist["Dizzy Miss Grizzly"] = 60
fatelist["Double Dhara"] = 60
fatelist["Keeping More Peace"] = 60
fatelist["Keeping the Peace"] = 60
fatelist["Roid Rage"] = 60
fatelist["Showing The Officers What For"] = 60
fatelist["Showing The Recruits What For"] = 60
fatelist["Showing the Commanders What For"] = 60
fatelist["Thank You for Not Mossling"] = 60
fatelist["Unbearable"] = 60
fatelist["Diakka Round"] = 61
fatelist["The Evil Seed"] = 61
fatelist["The Mail Must Get Through"] = 61
fatelist["The Morning After"] = 61
fatelist["The Secret Life of Plants"] = 61
fatelist["The Spiderweb Chronicles"] = 61
fatelist["Yes This Is Dogs"] = 61
fatelist["A Pain in the Neck"] = 67
fatelist["Ananta and Her Sisters"] = 67
fatelist["Flappy Berda"] = 67
fatelist["Get Sharp"] = 67
fatelist["M Bop"] = 67
fatelist["Pop the Trunk"] = 67
fatelist["Raisin' Hell"] = 67
fatelist["Really Don't Keratyrannos"] = 67
fatelist["The Antlion's Share"] = 67
fatelist["The Tele-tale Hunt"] = 67
fatelist["A Bone to Pick"] = 60
fatelist["A New Leaf"] = 60
fatelist["And the Bandits Played On"] = 60
fatelist["Attack of the Groans"] = 60
fatelist["Beat Boxes"] = 60
fatelist["Child's Plague"] = 60
fatelist["Churlish Chapuli"] = 60
fatelist["Das Bhoot"] = 60
fatelist["Days of Fluturini Past"] = 60
fatelist["Down with the Sickness"] = 60
fatelist["Moth to a Flame"] = 60
fatelist["Of Mice and Men"] = 60
fatelist["Resist Die Repeat"] = 60
fatelist["Salad Days"] = 60
fatelist["Venting"] = 60
fatelist["Winging It"] = 60
fatelist["Barbershoppe"] = 61
fatelist["Diceman Cometh"] = 61
fatelist["Stuck in the Muud"] = 61
fatelist["You Don't Know Jack"] = 61
fatelist["5-year Energy"] = 68
fatelist["Breakneck"] = 68
fatelist["Eat Big or Go Home"] = 68
fatelist["Fletching Returns"] = 68
fatelist["Forget-me-not"] = 68
fatelist["Home on the Range"] = 68
fatelist["Love Me Tindalos"] = 68
fatelist["Mouth For Water"] = 68
fatelist["Rattle and Humbaba"] = 68
fatelist["Slaughterwife-five"] = 68
fatelist["The Day of the Griffins"] = 68
fatelist["The Magitek Is Back"] = 68
fatelist["About Face"] = 69
fatelist["Ancelot's Fear"] = 69
fatelist["Ancelot's Finale"] = 69
fatelist["Ancelot's Folly"] = 69
fatelist["Dive In"] = 69
fatelist["Dude Where's My Karya"] = 69
fatelist["Dusk Till Abaddon"] = 69
fatelist["Enemy Territory"] = 69
fatelist["Fate No Morpho"] = 69
fatelist["Foul Bachelor Frogamander"] = 69
fatelist["Give Bees a Chance"] = 69
fatelist["I Can Feel the Earth Move"] = 69
fatelist["Kingsgrave"] = 69
fatelist["Lalla Land"] = 69
fatelist["Mazeless Runner"] = 69
fatelist["Minotaurs on My Mind"] = 69
fatelist["No Time Is a Good Time"] = 69
fatelist["OK Golem"] = 69
fatelist["Off Their Yabby"] = 69
fatelist["Old Bucket of Boruta"] = 69
fatelist["One Bad Mother Chukwa"] = 69
fatelist["Par for the Course"] = 69
fatelist["Pounding Salt"] = 69
fatelist["Sip When I'm Dead"] = 69
fatelist["Sisyphus Cooling"] = 69
fatelist["Sob Story"] = 69
fatelist["Taking Kurrea Business"] = 69
fatelist["Tall Tale"] = 69
fatelist["Tellus a Tale"] = 69
fatelist["The Smell That Leeched Her Heart"] = 69
fatelist["To Leech His Own"] = 69
fatelist["When It Pains It Pours"] = 69
fatelist["Who's Phoebad"] = 69
fatelist["Yabby Hunters"] = 69
fatelist["A Horse Outside"] = 70
fatelist["Agni's Philosophy"] = 62
fatelist["Another One Bites The Dust"] = 62
fatelist["Bilge-hold Jin"] = 62
fatelist["Clean Bill of Health"] = 62
fatelist["Crab Mentality"] = 62
fatelist["Days of Plunder"] = 62
fatelist["Forever Younglier"] = 62
fatelist["Jumping the Shark"] = 62
fatelist["Never Say Daimyo"] = 62
fatelist["Pool Party"] = 62
fatelist["Princess Princess"] = 62
fatelist["Raise the Red Flag"] = 62
fatelist["Ranging Bull"] = 62
fatelist["Ray Band"] = 62
fatelist["Soak Up the Sun"] = 62
fatelist["The Big Banquet Theory"] = 62
fatelist["The Coral High Ground"] = 62
fatelist["The F-bomb"] = 62
fatelist["Turtle Power"] = 62
fatelist["Uncivil Serpents"] = 62
fatelist["Wet"] = 62
fatelist["Double Dream Clams"] = 63
fatelist["Independence Ray"] = 63
fatelist["Kill the Messenger"] = 63
fatelist["Lay of the Lang"] = 63
fatelist["Quoth The Raven"] = 63
fatelist["Red Cliff"] = 63
fatelist["Sailor Marooned"] = 63
fatelist["There Be Dragonflies"] = 63
fatelist["Treasure Island"] = 63
fatelist["A Fish to Fry"] = 64
fatelist["A Tisket A Tasket"] = 64
fatelist["Dead To Rites Kiyofusa"] = 64
fatelist["Dead To Rites Koja"] = 64
fatelist["Deep Red Sea"] = 64
fatelist["Falling Drown"] = 64
fatelist["Footing the Bills"] = 64
fatelist["Freedom Flies"] = 64
fatelist["Get Ready For a Nu Wave"] = 64
fatelist["In One Basket"] = 64
fatelist["Killer Apsaras"] = 64
fatelist["Leave the Meters Running"] = 64
fatelist["Linquan Continental"] = 64
fatelist["Long Hands Long Fingers"] = 64
fatelist["Motherly Love"] = 64
fatelist["Oneblade Wonder"] = 64
fatelist["Raze the Red Lantern"] = 64
fatelist["Rice and Shine"] = 64
fatelist["Stay of Eggsecution"] = 64
fatelist["The Long and Rhino Road"] = 64
fatelist["The Virgin Homicides"] = 64
fatelist["This Is a Da This Is a Peng"] = 64
fatelist["Tiger Need"] = 64
fatelist["To Catch a Weasel"] = 64
fatelist["Tsurubebi Snugly"] = 64
fatelist["Crying Wolves"] = 67
fatelist["Curiosity Killed the Catfish"] = 67
fatelist["Goodwill Hunterling"] = 67
fatelist["Mada's Ilk"] = 67
fatelist["Mister Whiskers"] = 67
fatelist["More to Offer"] = 67
fatelist["Outfoxed"] = 67
fatelist["Ragoh To Extremes"] = 67
fatelist["Scared Straightheart"] = 67
fatelist["Tora Tora Tora"] = 67
fatelist["Très Bian"] = 67
fatelist["Wolves of a Feather"] = 67
fatelist["Foxy Lady"] = 70
fatelist["A Good Day To Die"] = 65
fatelist["A Tall Order"] = 65
fatelist["A Walk Through the Valley"] = 65
fatelist["Duck and Cover"] = 65
fatelist["Eat You Better"] = 65
fatelist["Good Day to Mate"] = 65
fatelist["Hook Line and Stinker"] = 65
fatelist["Killing Dzo"] = 65
fatelist["Live for the Mettle"] = 65
fatelist["Man to Mangas"] = 65
fatelist["More than You Chaochu"] = 65
fatelist["Not Just a Tribute"] = 65
fatelist["Purbol Reign"] = 65
fatelist["Rock for Food"] = 65
fatelist["The Dataqi Chronicles Decimation"] = 65
fatelist["The Dataqi Chronicles Declarations"] = 65
fatelist["The Dataqi Chronicles Departures"] = 65
fatelist["The Dataqi Chronicles Deprivation"] = 65
fatelist["The Dataqi Chronicles Desperation"] = 65
fatelist["The Dataqi Chronicles Deterrence"] = 65
fatelist["The Dataqi Chronicles Diplomacy"] = 65
fatelist["The Dataqi Chronicles Displacement"] = 65
fatelist["The Dataqi Chronicles Distractions"] = 65
fatelist["The Dataqi Chronicles Distress"] = 65
fatelist["The Dataqi Chronicles Divergence"] = 65
fatelist["The Dataqi Chronicles Dominion"] = 65
fatelist["The Dataqi Chronicles Duty"] = 65
fatelist["The State of Reunion"] = 65
fatelist["They Shall Not Want"] = 65
fatelist["Wham Bam Thank You Mammoth"] = 65
fatelist["Wooly Boys"] = 65
fatelist["Burn After Evening"] = 66
fatelist["Buzzkill"] = 66
fatelist["Cold Comes the Wind"] = 66
fatelist["Don't You Mean Kirata"] = 66
fatelist["Feel the Noise"] = 66
fatelist["Fired"] = 66
fatelist["Get Out The Vochu"] = 66
fatelist["Hat's Off"] = 66
fatelist["Hey Manzasiri"] = 66
fatelist["Khan Artist"] = 66
fatelist["Razing the Baras"] = 66
fatelist["The Fangover"] = 66
fatelist["A Beast among Men"] = 71
fatelist["Behind Anemone Lines"] = 71
fatelist["Calm a Chameleon"] = 71
fatelist["Creeping Nightshade"] = 71
fatelist["Cry Not Wolf"] = 71
fatelist["Deadly Nightshade"] = 71
fatelist["Don't Feed the Gremlins"] = 71
fatelist["Draconian Measures"] = 71
fatelist["Economic Peril"] = 71
fatelist["Flowering Nightshade"] = 71
fatelist["Little Gate of Horrors"] = 71
fatelist["Looming Nightshade"] = 71
fatelist["Pick-up Sticks"] = 71
fatelist["Subtle Nightshade"] = 71
fatelist["Toxic Nightshade"] = 71
fatelist["Bitter Barley"] = 70
fatelist["JELL-NO"] = 70
fatelist["One-punch Mantis"] = 70
fatelist["Roadside Dinner"] = 70
fatelist["Shadow Over Stilltide"] = 70
fatelist["The Wright Stuff"] = 70
fatelist["A Family Most Formidable"] = 78
fatelist["Foes Most Formidable"] = 78
fatelist["Ironbeard Builders Rebuilt"] = 78
fatelist["Ironbeard Builders Resist"] = 78
fatelist["Ironbeard Builders Revolt"] = 78
fatelist["Knockout"] = 78
fatelist["Not Today"] = 78
fatelist["Season of Our Discord"] = 78
fatelist["The Amity Village Horror"] = 78
fatelist["A Finale Most Formidable"] = 80
fatelist["Bear Necessities"] = 72
fatelist["Hedge Mazed"] = 72
fatelist["Locus Terribilis"] = 72
fatelist["Mad Magic"] = 72
fatelist["Once Upon a Time"] = 72
fatelist["Thrice Upon a Time"] = 72
fatelist["Twice Upon a Time"] = 72
fatelist["Weave 'Em and Weep"] = 72
fatelist["Back and Fuath"] = 73
fatelist["Breaking the Fuath Wall"] = 73
fatelist["Brute Fuath"] = 73
fatelist["Frog Standard"] = 73
fatelist["Fuath of Habit"] = 73
fatelist["Fuath to Be Reckoned With"] = 73
fatelist["Go Fuath a Conqueror"] = 73
fatelist["Great Daens"] = 73
fatelist["Bayawak Attack"] = 70
fatelist["Cactus Makes Perfect"] = 70
fatelist["Harbingers of Bloom"] = 70
fatelist["Pray Destroy the Waking Sands"] = 70
fatelist["Reptilian Roadblock"] = 70
fatelist["Scavengers Hunted"] = 70
fatelist["Theft from Above"] = 70
fatelist["Tolba No. 1"] = 70
fatelist["Armadillo Peccadillo"] = 76
fatelist["Baddie Longlegs"] = 76
fatelist["Bloody Simple"] = 76
fatelist["Let's Dance (with Swords)"] = 76
fatelist["Sand and Deliver"] = 76
fatelist["The Elderblade"] = 76
fatelist["This Time It's Personal"] = 76
fatelist["Anti-eruption Measures"] = 77
fatelist["The Odd Couple"] = 77
fatelist["Attack of the Killer Tomatl"] = 74
fatelist["Dark Matters"] = 74
fatelist["I'll Be Bark"] = 74
fatelist["Picking up the Pieces"] = 74
fatelist["Six Fulm Turkeys"] = 74
fatelist["We Are Venom"] = 74
fatelist["Attack the Block"] = 75
fatelist["Barking Mad"] = 75
fatelist["Creepy Crawlers"] = 75
fatelist["Monkeying Around"] = 75
fatelist["Nest of Kin"] = 75
fatelist["Pluck of the Draw"] = 75
fatelist["Queen of the Harpies"] = 75
fatelist["Shot Through the Hart"] = 75
fatelist["The End of the Sentry"] = 75
fatelist["Tojil Annihilation"] = 75
fatelist["Tojil Carnage"] = 75
fatelist["Tojil Eclipse"] = 75
fatelist["Tojil War"] = 75
fatelist["A Lot to Swallow"] = 79
fatelist["Coral Support"] = 79
fatelist["Hydrozoan of the Enders"] = 79
fatelist["Lookin' Back on the Track"] = 79
fatelist["Low Coral Fiber"] = 79
fatelist["My Friend's Enemy is Anemone of Mine"] = 79
fatelist["Natural Prawn Killers"] = 79
fatelist["Nothing Like a Trappin' Life"] = 79
fatelist["Ondo of Blood"] = 79
fatelist["Pearls Apart"] = 79
fatelist["The Devil in the Deep Blue Sea"] = 79
fatelist["The Nets Best Thing"] = 79
fatelist["The Seashells He Sells"] = 79
fatelist["Where Has the Dagon"] = 79
fatelist["The Head the Tail the Whole Damned Thing"] = 80
fatelist["Bite the Pellet"] = 80
fatelist["Homecrawling"] = 80
fatelist["Incident Files Seeds of Chaos"] = 80
fatelist["Let It Grow"] = 80
fatelist["Acid in Flight Shepherd's Fright"] = 81
fatelist["Breakfast Lunch and Dinner"] = 81
fatelist["Incident Files Steamed Vegetable"] = 81
fatelist["The Hills Are Alive"] = 81
fatelist["Incident Files Elemental Attraction"] = 85
fatelist["Incident Files Ice of the Tiger"] = 85
fatelist["Empty the Nest"] = 88
fatelist["Moisture Farming"] = 88
fatelist["Residual Complications"] = 88
fatelist["Sheaves on the Wind"] = 88
fatelist["The Frailty of Life"] = 88
fatelist["Wasted XIV"] = 88
fatelist["Full Petal Alchemist Perilous Pickings"] = 80
fatelist["Full Petal Alchemist Risky Return"] = 80
fatelist["Shiver and Shock"] = 80
fatelist["The Accursed Kanabhuti"] = 80
fatelist["When Gaja Go Gaga"] = 80
fatelist["I Am the Valras"] = 81
fatelist["Of Claws and Gall"] = 81
fatelist["The Little Nanka That Could"] = 81
fatelist["Devout Pilgrims vs. the Apalala"] = 85
fatelist["Devout Pilgrims vs. the Jungle Lizards"] = 85
fatelist["Mesmerizing Moths"] = 85
fatelist["Monkeys on Your Back"] = 85
fatelist["Peek-a-Bhujamga"] = 85
fatelist["Return of the Tyrant"] = 85
fatelist["Stalkers in the Shroud"] = 85
fatelist["Swipe Eft"] = 85
fatelist["Devout Pilgrims vs. Daivadipa"] = 90
fatelist["A Snowball's Chance"] = 82
fatelist["Amazing Crates"] = 82
fatelist["Artificial Malevolence 15 Minutes to Comply"] = 82
fatelist["Artificial Malevolence The Drone Army"] = 82
fatelist["Nettle Gear Solid"] = 82
fatelist["Not Yeti"] = 82
fatelist["Roses Are Red Violence Is Due"] = 82
fatelist["Trespassers Will Be Eaten"] = 82
fatelist["A Bit of a Problem"] = 83
fatelist["Artificial Malevolence Mighty Metatron"] = 83
fatelist["Artificial Malevolence Unmanned Aerial Villains"] = 83
fatelist["Exterminate Exterminate"] = 83
fatelist["Parts Unknown"] = 83
fatelist["Rocker Roller Out-of-controller"] = 83
fatelist["Stray Dog Strut"] = 83
fatelist["The Man with the Golden Son"] = 83
fatelist["Cactus What You Preach"] = 83
fatelist["Droids Gone Wild"] = 83
fatelist["Mantids on the Moon"] = 83
fatelist["One Giant Weep"] = 83
fatelist["The Stones of Silence"] = 83
fatelist["The Strolling Stones"] = 83
fatelist["Head Empty Only Thoughts"] = 84
fatelist["Hunger Strikes"] = 84
fatelist["Lepus Lamentorum Cleaner Catastrophe"] = 84
fatelist["Lepus Lamentorum Crazy Contraption"] = 84
fatelist["Lepus Lamentorum Dynamite Disaster"] = 84
fatelist["Scrapping the Scrapers"] = 84
fatelist["Taking Care of the Caretakers"] = 84
fatelist["Tech Support Cull"] = 84
fatelist["What a Thrill"] = 84
fatelist["Butterfly Kisses of Death"] = 86
fatelist["Drawing the Thunderstroke"] = 86
fatelist["Grand Designs Aigokeros"] = 86
fatelist["Grand Designs Io"] = 86
fatelist["Nature's Staunch Protector"] = 86
fatelist["Ophion-mania"] = 86
fatelist["The Rustling of Murderous Leaves"] = 86
fatelist["You Hurt My Researcher Prepare to Die"] = 86
fatelist["Eurydike All Bark No Bite"] = 87
fatelist["Grand Designs The Newest of New"] = 87
fatelist["Grand Designs Unknown Execution"] = 87
fatelist["King of the Hill"] = 87
fatelist["So Sorry Sokles"] = 87
fatelist["There's a Snake in My Water Supply!"] = 87
fatelist["Why Did It Have to Be Medusae?"] = 87
fatelist["(No) Wind beneath Our Wings"] = 89
fatelist["Beacons of Lost Hope"] = 89
fatelist["Dead Inside"] = 89
fatelist["Fallen from Grace"] = 89
fatelist["Far from the Madding Horde"] = 89
fatelist["Nevermore"] = 89
fatelist["Omicron Recall Comms Expansion"] = 89
fatelist["Omicron Recall Secure Connection"] = 89
fatelist["Only Just Begun"] = 89
fatelist["Sound and Fury"] = 89
fatelist["Staring into the Void"] = 89
fatelist["Wings of Glory"] = 89
fatelist["Omicron Recall Killing Order"] = 90
fatelist["A Twist of Fête"] = 1
fatelist["Made of Softer Stuff"] = 1
fatelist["Shear-a-Yak"] = 1
fatelist["Toy Hunter"] = 1
fatelist["Presents of Mind"] = 1
fatelist["Fire Suppression"] = 90
fatelist["Panaq Attack"] = 90
fatelist["Ratels So Ravenous"] = 90
fatelist["Birds Up"] = 91
fatelist["Megamaguey Mayhem"] = 91
fatelist["Pasture Expiration Date"] = 91
fatelist["Too Irate to Migrate"] = 91
fatelist["Weeding the Garden"] = 91
fatelist["Wolf Parade"] = 91
fatelist["A Valiant Duel"] = 93
fatelist["Big Storm Coming"] = 93
fatelist["By Your Powers Combined"] = 93
fatelist["Claws and Effect"] = 93
fatelist["Gust Stop Already"] = 93
fatelist["Lay Off the Horns"] = 93
fatelist["Salty Showdown"] = 93
fatelist["So Long Suckers"] = 93
fatelist["Young Volcanoes"] = 93
fatelist["Combing the Area"] = 90
fatelist["Crocs of the Creek"] = 90
fatelist["Reeds in Need"] = 90
fatelist["There's Always a Bigger Beast"] = 90
fatelist["This Kills the Craklaw"] = 90
fatelist["Feathery Dustup"] = 91
fatelist["The Pama-yawa Dilemma"] = 91
fatelist["Toucalibri at That Game"] = 91
fatelist["Bandit Tax Paid in Full"] = 92
fatelist["Borne on the Backs of Burrowers"] = 92
fatelist["Caphunter Mushroom Muncher"] = 92
fatelist["Mole Patrol"] = 92
fatelist["Putting the Fun in Fungicide"] = 92
fatelist["Ruffling Feathers"] = 92
fatelist["Sayona Your Prayers"] = 92
fatelist["Sting Operation"] = 92
fatelist["Tax Dodging"] = 92
fatelist["Tegu or Not Tegu"] = 92
fatelist["Could've Found Something Bigger"] = 94
fatelist["Escape Shroom"] = 94
fatelist["Fright or Flight"] = 94
fatelist["I Ain't Afraid of No Ghost"] = 94
fatelist["La Selva se lo Llevó"] = 94
fatelist["Moths Are Tough"] = 94
fatelist["My Star"] = 94
fatelist["Najool of Denial"] = 94
fatelist["Porting Is Such Sweet Sorrow"] = 94
fatelist["Sick Ornery Wivres"] = 94
fatelist["Stabbing Gutward"] = 94
fatelist["Stick it to the Mantis"] = 94
fatelist["The Departed"] = 94
fatelist["The Fruit of the Problem"] = 94
fatelist["The Spawning"] = 94
fatelist["Trial by Firedance"] = 94
fatelist["Claw and Order"] = 95
fatelist["Dhara Dared"] = 95
fatelist["Gonna Have Me Some Fur"] = 95
fatelist["Nopal Hunters"] = 95
fatelist["That's Me and the Porter"] = 95
fatelist["The Dead Never Die"] = 95
fatelist["The Serpentlord Stirs"] = 95
fatelist["You Are What You Drink"] = 95
fatelist["A Raptor Runs Through It"] = 96
fatelist["A Tortoise of a Tale"] = 96
fatelist["Ain't What I Herd"] = 96
fatelist["Breaking the Jaw"] = 96
fatelist["Helms off to the Bull"] = 96
fatelist["The Serpentlord Sires"] = 96
fatelist["The Serpentlord Speaks"] = 96
fatelist["The Serpentlord Suffers"] = 96
fatelist["The Serpentlord Seethes"] = 100
fatelist["A Scythe to an Axe Fight"] = 97
fatelist["Anger Issues"] = 97
fatelist["Days of Thunder"] = 97
fatelist["Hack the Planet"] = 97
fatelist["It's Super Defective"] = 97
fatelist["License to Dill"] = 97
fatelist["Running of the Katobleps"] = 97
fatelist["Ware the Wolves"] = 97
fatelist["(Got My Eye) Set on You"] = 98
fatelist["Domo Arigato"] = 98
fatelist["Mi Casa Es Mi Casa"] = 98
fatelist["Mr. Roboto"] = 98
fatelist["Old Stampeding Grounds"] = 98
fatelist["print('I hate snakes')"] = 98
fatelist["Pulling the Wool"] = 98
fatelist["To Each His Drone"] = 98
fatelist["When It's So Salvage"] = 98
fatelist["Canal Carnage"] = 99
fatelist["Critical Corruption"] = 99
fatelist["Feed Me Sentries"] = 99
fatelist["Horse in the Round"] = 99
fatelist["Invaders from Asyle"] = 99
fatelist["Mascot March"] = 99
fatelist["Mascot Mayhem"] = 99
fatelist["No Loitering"] = 99
fatelist["Plumbers Don't Fear Slimes"] = 99
fatelist["Scattered Memories"] = 99
fatelist["Seeds of Tomorrow"] = 99
fatelist["Slime to Die"] = 99
fatelist["Mascot Murder"] = 100