Tracker:AddLocations("locations/Amh Araeng.json")
Tracker:AddLocations("locations/Azys Lla.json")
Tracker:AddLocations("locations/Central Shroud.json")
Tracker:AddLocations("locations/Central Thanalan.json")
Tracker:AddLocations("locations/Coerthas Central Highlands.json")
Tracker:AddLocations("locations/Coerthas Western Highlands.json")
Tracker:AddLocations("locations/East Shroud.json")
Tracker:AddLocations("locations/Eastern La Noscea.json")
Tracker:AddLocations("locations/Eastern Thanalan.json")
Tracker:AddLocations("locations/Elpis.json")
Tracker:AddLocations("locations/Eulmore.json")
Tracker:AddLocations("locations/Foundation.json")
Tracker:AddLocations("locations/Garlemald.json")
Tracker:AddLocations("locations/Goal.json")
Tracker:AddLocations("locations/Heritage Found.json")
Tracker:AddLocations("locations/Il Mheg.json")
Tracker:AddLocations("locations/Kholusia.json")
Tracker:AddLocations("locations/Kozamauka.json")
Tracker:AddLocations("locations/Kugane.json")
Tracker:AddLocations("locations/Labyrinthos.json")
Tracker:AddLocations("locations/Lakeland.json")
Tracker:AddLocations("locations/Limsa Lominsa Lower Decks.json")
Tracker:AddLocations("locations/Limsa Lominsa Upper Decks.json")
Tracker:AddLocations("locations/Living Memory.json")
Tracker:AddLocations("locations/Lower La Noscea.json")
Tracker:AddLocations("locations/Mare Lamentorum.json")
Tracker:AddLocations("locations/Middle La Noscea.json")
Tracker:AddLocations("locations/Mist.json")
Tracker:AddLocations("locations/Mor Dhona.json")
Tracker:AddLocations("locations/New Gridania.json")
Tracker:AddLocations("locations/North Shroud.json")
Tracker:AddLocations("locations/Northern Thanalan.json")
Tracker:AddLocations("locations/Old Gridania.json")
Tracker:AddLocations("locations/Old Sharlayan.json")
Tracker:AddLocations("locations/Outer La Noscea.json")
Tracker:AddLocations("locations/Radz-at-Han.json")
Tracker:AddLocations("locations/Rhalgrs Reach.json")
Tracker:AddLocations("locations/Shaaloani.json")
Tracker:AddLocations("locations/Shirogane.json")
Tracker:AddLocations("locations/Solution Nine.json")
Tracker:AddLocations("locations/South Shroud.json")
Tracker:AddLocations("locations/Southern Thanalan.json")
Tracker:AddLocations("locations/Thavnair.json")
Tracker:AddLocations("locations/The Azim Steppe.json")
Tracker:AddLocations("locations/The Churning Mists.json")
Tracker:AddLocations("locations/The Crystarium.json")
Tracker:AddLocations("locations/The Dravanian Forelands.json")
Tracker:AddLocations("locations/The Dravanian Hinterlands.json")
Tracker:AddLocations("locations/The Fringes.json")
Tracker:AddLocations("locations/The Goblet.json")
Tracker:AddLocations("locations/The Lavender Beds.json")
Tracker:AddLocations("locations/The Lochs.json")
Tracker:AddLocations("locations/The Peaks.json")
Tracker:AddLocations("locations/The Pillars.json")
Tracker:AddLocations("locations/The Raktika Greatwood.json")
Tracker:AddLocations("locations/The Ruby Sea.json")
Tracker:AddLocations("locations/The Sea of Clouds.json")
Tracker:AddLocations("locations/The Tempest.json")
Tracker:AddLocations("locations/Tuliyollal.json")
Tracker:AddLocations("locations/Uldah Steps of Nald.json")
Tracker:AddLocations("locations/Ultima Thule.json")
Tracker:AddLocations("locations/Upper La Noscea.json")
Tracker:AddLocations("locations/Urqopacha.json")
Tracker:AddLocations("locations/Western La Noscea.json")
Tracker:AddLocations("locations/Western Thanalan.json")
Tracker:AddLocations("locations/Yak Tel.json")
Tracker:AddLocations("locations/Yanxia.json")
Tracker:AddLocations("locations/Overworld.json")
